#!/bin/bash

case "$(basename "$0")" in
"cc" | "gcc")
    PROG="${ORIG_CC?"No original"}"
    EXTRA="--coverage -lgcov"
    ;;
"c++" | "g++")
    PROG="${ORIG_CXX?"No original"}"
    EXTRA="--coverage -lgcov"
    ;;
*)
    exit 1
    ;;
esac


# If we aren't recording coverage, reset the extra args.
if [ ! -f /COVERAGE ]
then
	EXTRA=""
fi

"$PROG" $EXTRA "$@"
