#!/bin/bash

echo "export ORIG_CC=`readlink $( readlink /etc/alternatives/cc) `" >> /etc/profile.d/sh-profile.sh
echo "export ORIG_CXX=`readlink $( readlink /etc/alternatives/c++) `" >> /etc/profile.d/sh-profile.sh

rm /usr/bin/cc && cp /usr/bin/gcc-cov /usr/bin/cc
rm /usr/bin/gcc && cp /usr/bin/gcc-cov /usr/bin/gcc
rm /usr/bin/g++ && cp /usr/bin/gcc-cov /usr/bin/g++
rm /usr/bin/i686-linux-gnu-gcc && cp /usr/bin/gcc-cov /usr/bin/i686-linux-gnu-gcc
rm /usr/bin/i686-linux-gnu-g++ && cp /usr/bin/gcc-cov /usr/bin/i686-linux-gnu-g++
