#!/bin/bash

case "$(basename "$0")" in
"cc" | "gcc")
    PROG="${ORIG_CC?"No original"}"
    EXTRA="--coverage -lgcov"
    ;;
"c++" | "g++")
    PROG="${ORIG_CXX?"No original"}"
    EXTRA="--coverage -lgcov"
    ;;
*)
    exit 1
    ;;
esac


# Always run a normal execution, even if we are adding coverage
# instrumentation.  This is so we get the right output for commands
# like gcc -v.
"$PROG" "$@"

if [ -f /COVERAGE ]
then
    # If we are recording coverage, then run again with the coverage
    # flags, but do so silently.  The idea is that if we are actually
    # doing compilation, we'll overwrite the non-instrumented file.
    # If we're doing something like gcc -v, this will have no effect.
    "$PROG" $EXTRA "$@"
fi
