#!/bin/bash

echo "export ORIG_CC=`readlink $( readlink /etc/alternatives/cc) `" >> /etc/bash.bashrc
echo "export ORIG_CXX=`readlink $( readlink /etc/alternatives/c++) `" >> /etc/bash.bashrc

for f in /usr/bin/{cc,gcc,g++,i686-linux-gnu-gcc,i686-linux-gnu-g++}
do
    rm $f && cp /usr/bin/gcc-cov $f
done
